version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '8888:8888'
    volumes:
      - ./data/notebook:/home/jovyan
